#! /usr/bin/bash


handel_FK(){ 
    # Parameters: original_table_full_path


    
    table_name=${1##*/}
    table_path=$(dirname "$1")
    meta_path="$table_path"
    meta_files="$meta_path/meta_*"
    
    echo $table_path
     
    # Load PKs of deleted rows into an array
    delete_file="$table_path/delete_tmp"
 	 
    for meta_tables in $meta_files; do
        echo "Processing file: $meta_tables"

        # Get FK column number referencing this table
        col_num=$(grep -w "FOREIGN KEY REFERENCES $table_name" "$meta_tables" | awk -F',' '{print $1}' | grep -o '[0-9]\+')
        echo "FK column number: $col_num"

        if [[ ! -z "$col_num" ]]; then
            last_meta_table=${meta_tables##*/}
            tablename=${last_meta_table#*_}
            echo $tablename
            awk -v col="$col_num" -v del_file="$delete_file" '
                BEGIN {
                    FS = OFS = ","
                    # read deleted PKs into an array
                    while ((getline line < del_file) > 0) {
                        delete_vals[line] = 1
                    }
                    close(del_file)
                }
                
                {
                    if (NR!=1 && $col in delete_vals)
                        $col = ""
                    print $0
                }' "$table_path/$tablename" > $table_path"/tmpfk" && mv $table_path"/tmpfk" "$table_path/$tablename"
        fi
    done
}



delete_from_atable() {
    read -p "Enter the table name to delete: " table_name
    meta_path=$1
    meta_files="$meta_path/meta_*"
    table_path=$1"/"
    if [[ -z "$table_name" ]]; then
        echo "Error: Table name is required."
        return 1
    fi

    if [[ ! -f "$table_path$table_name" ]]; then
        echo "Error: Table '$table_name' does not exist."
        return 1
    fi

    read -p "Enter the column name to make the delete depend on: " column_name
    col_num=$(tail -n +7 "$meta_path/meta_$table_name" | awk -F',' -v col="$column_name" '$2 == col {print NR }')



    
    echo "$col_num"
    if [[ -z "$col_num" ]]; then
            echo "can not find the column '$column_name' in table '$table_name'"
            return 1
    fi

    read -p "Enter the value to delete rows by: " value_to_delete

    awk -v col="$col_num" -v val="$value_to_delete" '
    BEGIN {
        FS = OFS = ","
    }
    {
        if (NR == 1 || $col != val)
            print $0
    }' "$table_path$table_name" > $tablepath"tmp" 
        
        
        PK_num=$(grep -w "PRIMARY KEY" "$meta_path/meta_$table_name" | awk -F',' '{print $1}' | grep -o '[0-9]\+')
        echo 'pk is ' $PK_num
        if [[  -z $PK_num ]] then
         	
 		cat $tablepath"tmp" >"$table_path$table_name" 
 		rm  $tablepath"tmp" 
 		return 1
        fi 

   
    awk ' 
    BEGIN {   
        FS = OFS = ","  
    }  
    {  
        if (NR != 1 && $'"$col_num"' == "'"$value_to_delete"'")   
            print $'"$PK_num"' 
    }' "$table_path$table_name" > $table_path"delete_tmp"

    cat $tablepath"tmp" >"$table_path$table_name" 
    rm $tablepath"tmp" 
    

 
    handel_FK "$table_path$table_name" 
 
   

}
delete_from_atable $1