#!/usr/bin/bash

ListDBs() {
    path="./DBs"
    user=$(whoami)
    user_dbs=()
    
    # Find user's databases
    for d in "$path"/${user}_*; do
        if [[ -d "$d" ]]; then
            dirname=$(basename "$d")
            clean_name="${dirname#*_}"
            user_dbs+=("$clean_name")
        fi
    done
    
    # Show with Zenity
    if [[ ${#user_dbs[@]} -gt 0 ]]; then
        zenity --info \
            --title="Your Databases" \
            --text="Your databases:\n$(printf '%s\n' "${user_dbs[@]}")" \
            --width=400 --height=300
    else
        zenity --info \
            --title="No Databases" \
            --text="You do not have any databases." \
            --width=350 --height=150
    fi
}

ListDBs
