#!/bin/bash

select_data() {

    table_path="$1"

    while true; do

        tables=$(ls "$table_path" 2>/dev/null | grep -v '^meta_')

        if [[ -z "$tables" ]]; then
            zenity --error --text="No tables found."
            return 1
        fi

        table=$(echo "$tables" | zenity --list \
            --title="Select Table" \
            --column="Tables" \
            --height=300 \
            --width=300)

        [[ -z "$table" ]] && return 0

        if [[ ! -f "$table_path/$table" ]]; then
            zenity --error --text="Table not found!"
            continue
        fi

        choice=$(zenity --list \
            --title="Select Operation" \
            --column="Option" --column="Description" \
            1 "Select all data" \
            2 "Select row by PRIMARY KEY")

        [[ -z "$choice" ]] && continue

        if [[ "$choice" == "1" ]]; then

	    zenity --text-info \
		--title="Table: $table" \
		--width=700 \
		--height=400 \
		< <(cat -n "$table_path/$table")



        elif [[ "$choice" == "2" ]]; then

            meta="$table_path/meta_$table"

            if [[ ! -f "$meta" ]]; then
                zenity --error --text="No metadata found. Cannot detect PRIMARY KEY."
                continue
            fi

            pk=$(awk -F',' '$4~/PRIMARY KEY/{print $2; exit}' "$meta")

            if [[ -z "$pk" ]]; then
                zenity --error --text="No PRIMARY KEY in this table."
                continue
            fi

            val=$(zenity --entry \
                --title="Search by Primary Key" \
                --text="Enter value for PRIMARY KEY ($pk):")

            [[ -z "$val" ]] && continue

            header=$(head -1 "$table_path/$table")
            IFS=',' read -r -a cols <<< "$header"

            pos=0
            for i in "${!cols[@]}"; do
                [[ "${cols[i]}" == "$pk" ]] && { pos=$((i+1)); break; }
            done

            [[ "$pos" -eq 0 ]] && {
                zenity --error --text="PRIMARY KEY column not found."
                continue
            }

            line_num=$(awk -F',' -v col="$pos" -v val="$val" '$col == val {print NR}' "$table_path/$table")

            if [[ -n "$line_num" ]]; then
                result=$(sed -n "${line_num}p" "$table_path/$table")
                zenity --info \
                    --title="Result Found" \
                    --text="Header:\n$header\n\nRow:\n$result"
            else
                zenity --warning --text="No matching row found."
            fi
        else
            zenity --error --text="Invalid choice."
            return 1
        fi

        zenity --question --text="Do you want to select again?"
        [[ $? -ne 0 ]] && break
    done
}

select_data "$1"
